name: Convert Videos to HLS

on:
  workflow_dispatch:
  push:
    paths:
      - "*.mp4"
      - "*.mkv"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Convert videos
        run: |
          mkdir -p output
          for f in *.mp4 *.mkv; do
            if [ -f "$f" ]; then
              name=$(basename "$f" | sed 's/\.[^.]*$//')
              ffmpeg -i "$f" -profile:v baseline -level 3.0 -start_number 0 -hls_time 10 -hls_list_size 0 -f hls "output/$name.m3u8"
            fi
          done

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./output
